CREATE TABLE taskn (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL,
	content TEXT NOT NULL,
	schedule DATETIME NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)


-- 20240824
ALTER TABLE taskn ADD col_created_at datetime;
